### ISSUE TITLE
Dynamic load libraries for external functions

### ISSUE THREAD

**Issue by Grillo-0** [vinumdoc/vinum#16]
We want the user to be able to use programming languages to code its functions. This could be done by giving shared libraries to the compiler that will register new functions.

# Use Example

`vinumc doc.vin --with lib.so`

# Uses

This also could be useful for writing the standard library (like the `date` function).

With this, we can implement the `exec` function, which will solve the #14 issue. 

# Implementation Details

## External Library API

The flag `--with` will be used to specify the shared lib file. This flag is the same one that is going to be used to add libs written in vinum, so a check to differentiate those two use cases is going to be needed.

> [!NOTE]
> The next part needs more thinking...

The library would need to implement a set of predetermined functions, this would be called the **External Library API**

This API would be called by the compiler to register the functions that the external library developer wants to create.

# TODO

- [ ] Specify the API needed
- [ ] Implement the infrastructure of external functions
- [ ] Implement the dynamic loading of libraries on the compiler

**Comment by artP2** [comment]
My initial thought is that the external functions will be of type ```char* (*Function) (char*);``` and the library will have to provide the following function ```LibraryDefinition expose_library();``` with the quantity and names of the functions, as defined in the helper's header:
```
typedef struct {
  int counter;
  char** names;
} LibraryDefinition;
```

With the helper implemented in the assigned branch we only need the name of the library and it returns a struct with the functions' names and pointers.

**Comment by Grillo-0** [comment]
> and the library will have to provide the following function `LibraryDefinition expose_library();` with the quantity and names of the functions, as defined in the helper's header:
> 
> ```
> typedef struct {
>   int counter;
>   char** names;
> } LibraryDefinition;
> ```


I had a different API in mind:

We could ~somehow~ provide a function to the library that registers a function pointer with a name, like this:


```c
void register_function(const char *name, Function f);
```

Then the library developer would simply register the functions with simple function call, like this:

```c
char* foo(char *_) {
    return "Hello world!";
}


void expose_library() {
    register_function("hello", foo);
}
```

> Note that the function name does not need to be equal to the one provided on the first
> argument.

I don't know if this exact API could be implemented (I tried yesterday to create a proof of concept
but hadn't got the time to make it work). But I think that something along those line is a more
simple API for the library developer and it gives more freedom to the implementation too.


What do you think?

**Comment by artP2** [comment]
> We could ~somehow~ provide a function to the library that registers a function pointer with a name, like this:
> 
> ```c
> void register_function(const char *name, Function f);
> ```
This may work if this pointer is the same as the one given by the dl handle. 

> ```c
> void expose_library() {
>     register_function("hello", foo);
> }
> ```
Although the assigning direct pointer feature needs to be studied, this way of registering functions can drastically simplify the implementation I've done.

I'll refactor the code to use it as follows, and if what you propose works, it will be easy to adapt.
> ```c
> void expose_library() {
>     register_function("foo");
> }
> ```

**Comment by Grillo-0** [comment]
I made comments about your implementation on #28

**Comment by artP2** [comment]
> We could ~somehow~ provide a function to the library that registers a function pointer with a name, like this:
> 
> ```c
> void register_function(const char *name, Function f);
> ```

I've tested it here and the pointer provided by the dl_handle and this one are the same, see below:
```
dl pointer: 0x7f1e0ec291c3
pointer: 0x7f1e0ec291c3
```

I've modified the code so that the library passes this pointer directly.

**Comment by artP2** [comment]
### The way the API looks to library developers in the current implementation is as follows:
Include ```library_api.h```.
Define functions of type ```char* (*function_pointer) (char*)```.
Call the macro ```DEFINE_LIBRARY``` this way:
 ``` c
DEFINE_LIBRARY(
    FUNCTION("function_name", function_pointer),
    FUNCTION("function_name2", function_pointer2)
    )
```

> Note: this is the way it is in the current implementation, it doesn't mean it should be this way.
